/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oodjassignment.reportgeneratorGUI;
import java.awt.Desktop;
import java.io.FileReader;
import java.util.Set;

import javax.swing.JOptionPane;

import com.mycompany.oodjassignment.classes.Student;
import com.mycompany.oodjassignment.functions.Database;
import com.mycompany.oodjassignment.functions.ReportGenerator;
import com.mycompany.oodjassignment.functions.SendEmail;
import com.mycompany.oodjassignment.usermanagement.gui.DashboardFrame;
import com.mycompany.oodjassignment.usermanagement.service.AuthenticationService;

/**
 *
 * @author ASUS
 */
public class ReportGeneratorPanel extends javax.swing.JFrame {                
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportGeneratorPanel.class.getName());
    private final Database database = new Database();
    private AuthenticationService authService;


    /**
     * Creates new form ReportGenerator1
     */
    public ReportGeneratorPanel() {
        this(null);
    }

    public ReportGeneratorPanel(AuthenticationService authService) {
        this.authService = authService;
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Report Generator");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Report Generator");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(242, 242, 242));

        jFormattedTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jFormattedTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jFormattedTextField1.setToolTipText("");
        jFormattedTextField1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Student ID");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Display Report");
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Academic report");

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1", "Semester 2", "Semester 3", "Semester 4 ", "Semester 5", "Semester 6", "Year 1", "Year 2", "Year 3" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Return");
        jButton2.setBorder(null);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Student Analytic");
        jButton3.setBorder(null);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Get the student ID from the text field
        String studentId = jFormattedTextField1.getText().trim().toUpperCase();

        // Validate the input
        if (studentId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Student ID", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if the student ID exists in the database of student grade
        else if (!database.studentExist(studentId)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Student ID.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get the selected option from the combo box
        String selectedOption = (String) jComboBox2.getSelectedItem();
        
        // Clearing the option str only take integer value
        if (selectedOption.toLowerCase().contains("year")) {

            int year = Integer.parseInt(selectedOption.replaceAll("[^0-9]", ""));
            
            // Display message if no courses found in the selected year
            if (!database.studentYearExist(studentId, year)) {
                // Find available years for this student to inform the user
                Set<Integer> availableYears = database.getAvailableYears(studentId);
                
                String availableYearsStr = "No courses found in the selected year.";
                availableYearsStr += " Available years: " + availableYears;
                
                JOptionPane.showMessageDialog(this, availableYearsStr, "No Data Found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            // Generate the yearly report
            try {
                String filePath = "data/student_report/student_yearly_report_" + studentId + "_year" + year + ".pdf";
                
                com.mycompany.oodjassignment.functions.ReportGenerator reportGenerator = 
                    new com.mycompany.oodjassignment.functions.ReportGenerator(filePath);
                
                reportGenerator.generateYearlyReport(studentId, year);
                
                // Automatically send email to the student with the generated report
                try {
                    // Get student information to get the email address
                    Student student = database.getStudent(studentId);
                    if (student != null) {
                        String studentEmail = student.getEmail();
                        
                        // Create a SendEmail instance and send the report as attachment
                        SendEmail emailSender = new SendEmail(studentEmail);
                        String subject = "Your Academic Report for Year " + year;
                        String message = "Dear " + student.getFirstName() + " " + student.getLastName() + ",\n\n" +
                                "Please find attached your academic report for Year " + year + ".\n" +
                                "Best regards,\nAcademic Office";

                        // this is required because the thread will show error is not final or not local
                        new Thread() {
                            public void run() {
                                emailSender.Pdf(subject, message, filePath);
                            }
                        }.start();
                        
                        
                        Desktop.getDesktop().open(new java.io.File(filePath));

                        JOptionPane.showMessageDialog(this, 
                            "Yearly report generated successfully at: " + filePath + 
                            "\n\nReport has been automatically sent to the student's email: " + studentEmail, 
                            "Success", 
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    } 
                    
                    else {
                        JOptionPane.showMessageDialog(this, 
                            "Yearly report generated successfully at: " + filePath +
                            "\n\nNote: Could not retrieve student information to send email automatically.", 
                            "Success with Warning", 
                            javax.swing.JOptionPane.WARNING_MESSAGE);
                    }
                } 
                
                catch (Exception emailException) {
                    JOptionPane.showMessageDialog(this, 
                        "Report generated successfully at: " + filePath +
                        "\n\nError sending email: " + emailException.getMessage(), 
                        "Report Generated with Email Error", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                    emailException.printStackTrace();
                }
            } 
            
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error generating report: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } 
        
        else {
            int selectedSemester = Integer.parseInt(selectedOption.trim().replaceAll("[^0-9]", ""));
            
            // If a specific semester is selected, check if the student has grades for that semester
            if (!database.studentSemesterExist(studentId, String.valueOf(selectedSemester))) {
                Set<Integer> avaibleSemesters = database.getAvailableSemesters(studentId);

                String availableSemestersStr = "No courses found in the selected semester.";
                availableSemestersStr += " Available semesters: " + avaibleSemesters;
                
                JOptionPane.showMessageDialog(this, availableSemestersStr, "No Data Found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            
            // Generate the report with the selected semester
            try {
                // Create a report generator instance and generate the report
                String filePath = "data/student_report/student_report_" + studentId + "_sem" + selectedSemester + ".pdf";

                ReportGenerator reportGenerator = new ReportGenerator(filePath);
                
                reportGenerator.generateReport(studentId, selectedSemester);
                
                // Automatically send email to the student with the generated report
                try {
                    // Get student information to get the email address
                    Student student = database.getStudent(studentId);
                    if (student != null) {
                        
                        // Create a SendEmail instance and send the report as attachment
                        SendEmail sendEmail = new SendEmail(student.getEmail());
                        String subject = "Your Academic Report for Semester " + selectedSemester;
                        String message = "Dear " + student.getFirstName() + " " + student.getLastName() + ",\n\n" +
                                "Please find attached your academic report for Semester " + selectedSemester + ".\n" +
                                "This report contains your academic performance for this semester.\n\n" +
                                "Best regards,\nAcademic Office";
                        
                        // creating a new thread to send email so that the UI will not freeze
                        new Thread(() -> 
                                sendEmail.Pdf(subject, message, filePath)
                        ).start();                      

                        Desktop.getDesktop().open(new java.io.File(filePath));
                        
                        JOptionPane.showMessageDialog(this, 
                            "Report generated successfully at: " + filePath + 
                            "\n\nReport has been automatically sent to the student's email: " + student.getEmail(), 
                            "Success", 
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    } 
                    
                    else {
                        JOptionPane.showMessageDialog(this, 
                            "Report generated successfully at: " + filePath +
                            "\n\nNote: Could not retrieve student information to send email automatically.", 
                            "Success with Warning", 
                            javax.swing.JOptionPane.WARNING_MESSAGE);
                    }
                } 
                
                catch (Exception emailException) {
                    JOptionPane.showMessageDialog(this, 
                        "Report generated successfully at: " + filePath +
                        "\n\nError sending email: " + emailException.getMessage(), 
                        "Report Generated with Email Error", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                    emailException.printStackTrace();
                }
            } 
            
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error generating report: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Open the Student Performance Dashboard (chart)
        StudentPerformancePanel studentPerformancePanel = new StudentPerformancePanel();
        studentPerformancePanel.setReportGeneratorPanel(this); // Pass reference to ReportGeneratorPanel
        studentPerformancePanel.setVisible(true);
        setVisible(false); // Hide current window
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (authService == null) {
            JOptionPane.showMessageDialog(this,
                    "Return Failed, no authentication service",
                    "Missing Session",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        DashboardFrame dashboardFrame = new DashboardFrame(authService);
        dashboardFrame.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReportGeneratorPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
