/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oodjassignment.usermanagement.gui;

import com.mycompany.oodjassignment.AcademicOfficerGUI.CourseRecovery;
import com.mycompany.oodjassignment.Classes.User;
import com.mycompany.oodjassignment.Classes.UserRole;
import com.mycompany.oodjassignment.Helpers.Database;
import com.mycompany.oodjassignment.academicperformanceGUI.AcademicPerformancePanel;
import com.mycompany.oodjassignment.usermanagement.service.AuthenticationService;
import com.mycompany.oodjassignment.Eligibility.EligibilityMain;

/**
 *
 * @author willy
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private final AuthenticationService authService;
    private final User currentUser;

    public DashboardFrame(AuthenticationService authService) {
        this.authService = authService;
        this.currentUser = authService.getCurrentUser();
        initComponents();
        setLocationRelativeTo(null);
        configureDashboard();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        userManagementButton = new javax.swing.JButton();
        eligibilityButton = new javax.swing.JButton();
        academicReportButton = new javax.swing.JButton();
        recoveryPlanButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(0, 128, 236));
        headerPanel.setPreferredSize(new java.awt.Dimension(400, 80));

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setText("Welcome to CRS");

        roleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(255, 255, 255));
        roleLabel.setText("Role");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(welcomeLabel)
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roleLabel)
                .addGap(54, 54, 54))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleLabel)
                .addGap(12, 12, 12))
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setBackground(new java.awt.Color(240, 248, 255));
        buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        infoLabel.setForeground(new java.awt.Color(153, 153, 153));
        infoLabel.setText("Select a function to continue.");

        userManagementButton.setBackground(new java.awt.Color(70, 130, 180));
        userManagementButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        userManagementButton.setText("User Management");
        userManagementButton.setOpaque(true);
        userManagementButton.setPreferredSize(new java.awt.Dimension(233, 40));
        userManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagementButtonActionPerformed(evt);
            }
        });

        eligibilityButton.setBackground(new java.awt.Color(255, 153, 51));
        eligibilityButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        eligibilityButton.setText("Eligibility & Enrollment");
        eligibilityButton.setOpaque(true);
        eligibilityButton.setPreferredSize(new java.awt.Dimension(233, 40));
        eligibilityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eligibilityButtonActionPerformed(evt);
            }
        });

        academicReportButton.setBackground(new java.awt.Color(204, 51, 255));
        academicReportButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        academicReportButton.setText("Academic Report");
        academicReportButton.setOpaque(true);
        academicReportButton.setPreferredSize(new java.awt.Dimension(233, 40));
        academicReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                academicReportButtonActionPerformed(evt);
            }
        });

        recoveryPlanButton.setBackground(new java.awt.Color(153, 255, 0));
        recoveryPlanButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        recoveryPlanButton.setText("Course Recovery Plan");
        recoveryPlanButton.setOpaque(true);
        recoveryPlanButton.setPreferredSize(new java.awt.Dimension(233, 40));
        recoveryPlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoveryPlanButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setPreferredSize(new java.awt.Dimension(110, 40));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(infoLabel)
                .addGap(148, 148, 148))
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userManagementButton, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(eligibilityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(academicReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recoveryPlanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addComponent(infoLabel)
                .addGap(18, 18, 18)
                .addComponent(userManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eligibilityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(academicReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recoveryPlanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(buttonPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        private void configureDashboard() {
        if (currentUser == null) {
            welcomeLabel.setText("Welcome to CRS");
            roleLabel.setText("Role: Unknown");
            disableAllButtons();
            return;
        }

        welcomeLabel.setText("Welcome, " + currentUser.getFullName());
        roleLabel.setText("Role: " + currentUser.getRole().getDisplayName());
        infoLabel.setText("Select a module to continue.");
        applyRolePermissions(currentUser.getRole());
    }

    private void applyRolePermissions(UserRole role) {
        boolean isAcademicOfficer = role == UserRole.ACADEMIC_OFFICER;
        boolean isCourseAdministrator = role == UserRole.COURSE_ADMINISTRATOR;

        userManagementButton.setVisible(isAcademicOfficer || isCourseAdministrator);
        eligibilityButton.setVisible(isAcademicOfficer || isCourseAdministrator);
        academicReportButton.setVisible(isAcademicOfficer || isCourseAdministrator);
        recoveryPlanButton.setVisible(isAcademicOfficer);

        buttonPanel.revalidate();
        buttonPanel.repaint();
    }

    private void disableAllButtons() {
        userManagementButton.setEnabled(false);
        eligibilityButton.setEnabled(false);
        academicReportButton.setEnabled(false);
        recoveryPlanButton.setEnabled(false);
    }

    private void showComingSoonDialog(String moduleName) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            moduleName + " module will be available soon.",
            "Coming Soon",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }


    private void eligibilityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eligibilityButtonActionPerformed
        // Open the Eligibility & Enrollment GUI
        EligibilityMain eligibilityFrame = new EligibilityMain();
        eligibilityFrame.setVisible(true);
    }//GEN-LAST:event_eligibilityButtonActionPerformed

    private void academicReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_academicReportButtonActionPerformed
        // TODO add your handling code here:
        AcademicPerformancePanel generatorPanel = new AcademicPerformancePanel(authService);
        generatorPanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_academicReportButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        int choice = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            authService.logout();
            java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
            dispose();
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void recoveryPlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoveryPlanButtonActionPerformed
        Database database = new Database();
        CourseRecovery courseRecovery = new CourseRecovery(database, () ->
            java.awt.EventQueue.invokeLater(() -> {
                DashboardFrame dashboard = new DashboardFrame(authService);
                dashboard.setVisible(true);
            }), authService
        );
        
        javax.swing.JFrame courseRecoveryFrame = new javax.swing.JFrame("Course Recovery System");
        courseRecoveryFrame.setContentPane(courseRecovery.getCourseRecoveryPanel());
        courseRecoveryFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        courseRecoveryFrame.setSize(550, 400);
        courseRecoveryFrame.setLocationRelativeTo(this);
        courseRecoveryFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_recoveryPlanButtonActionPerformed

    private void userManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagementButtonActionPerformed
        UserManagementFrame frame = new UserManagementFrame(authService);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_userManagementButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton academicReportButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton eligibilityButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton recoveryPlanButton;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JButton userManagementButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
