/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.oodjassignment.usermanagement.gui;

import com.mycompany.oodjassignment.classes.User;
import com.mycompany.oodjassignment.functions.SendEmail;
import com.mycompany.oodjassignment.usermanagement.service.UserManager;
import com.mycompany.oodjassignment.usermanagement.util.PasswordUtil;
import javax.swing.JOptionPane;

public class PasswordChangeDialog extends javax.swing.JDialog {
    private final UserManager userManager;
    private final User targetUser;
    private boolean passwordChanged;

    public PasswordChangeDialog(java.awt.Frame parent, UserManager userManager, User targetUser) {
        super(parent, true);
        this.userManager = userManager;
        this.targetUser = targetUser;
        this.passwordChanged = false;
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPanel = new javax.swing.JPanel();
        newPasswordLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        newPasswordSeparatorLabel = new javax.swing.JLabel();
        confirmPasswordSeparatorLabel = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();
        passwordRequirementLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        changePasswordButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");
        setModal(true);
        setResizable(false);

        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        newPasswordLabel.setText("New Password");

        confirmPasswordLabel.setText("Confirm Password");

        newPasswordSeparatorLabel.setText(":");

        confirmPasswordSeparatorLabel.setText(":");

        newPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordFieldActionPerformed(evt);
            }
        });

        confirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFieldActionPerformed(evt);
            }
        });

        passwordRequirementLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        passwordRequirementLabel.setForeground(new java.awt.Color(102, 102, 102));
        passwordRequirementLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordRequirementLabel.setText("<html><center><i>Password must be at least 8 characters<br/>with uppercase, lowercase, and digit</i></center></html>");

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(confirmPasswordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmPasswordSeparatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formPanelLayout.createSequentialGroup()
                                .addComponent(newPasswordLabel)
                                .addGap(26, 26, 26)
                                .addComponent(newPasswordSeparatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(passwordRequirementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordLabel)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordSeparatorLabel))
                .addGap(29, 29, 29)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordLabel)
                    .addComponent(confirmPasswordSeparatorLabel)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(passwordRequirementLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(formPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setPreferredSize(new java.awt.Dimension(410, 60));

        changePasswordButton.setBackground(new java.awt.Color(70, 130, 180));
        changePasswordButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changePasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        changePasswordButton.setText("Change Password");
        changePasswordButton.setBorderPainted(false);
        changePasswordButton.setFocusPainted(false);
        changePasswordButton.setOpaque(true);
        changePasswordButton.setPreferredSize(new java.awt.Dimension(160, 35));
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setPreferredSize(new java.awt.Dimension(100, 35));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePassword() {
        String newPassword = new String(newPasswordField.getPassword());
        String confirmPassword = new String(confirmPasswordField.getPassword());
        
        if (newPassword.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please fill in all fields",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this,
                "New passwords do not match",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!PasswordUtil.isPasswordStrong(newPassword)) {
            JOptionPane.showMessageDialog(this,
                "Password must be at least 8 characters with uppercase, lowercase, and digit",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (targetUser == null) {
            JOptionPane.showMessageDialog(this,
                "No user selected for password change.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String hashedPassword = PasswordUtil.hashPassword(newPassword);
        targetUser.setPassword(hashedPassword);
        
        if (userManager.updateUser(targetUser)) {
            passwordChanged = true;
            
            // Send email notification about password change
            if (targetUser.getEmail() != null && !targetUser.getEmail().isEmpty()) {
                SendEmail sendEmail = new SendEmail(targetUser.getEmail());
                String emailSubject = "Password Changed Notification";
                String emailContent = "Dear " + targetUser.getFullName() + ",\n\n" +
                        "Your password has been successfully changed " + "\n\n" +
                        "If you did not do this change, please contact the system administrator immediately.\n\n" +
                        "Best regards,\n" +
                        "System Administrator";
                
                // using thread to prevent GUI freezing
                new Thread(() ->
                    sendEmail.Notification(emailSubject, emailContent)
                ).start();
            }
            
            JOptionPane.showMessageDialog(this,
                "Password changed successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                "Failed to change password. Please try again.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        changePassword();
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void newPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordFieldActionPerformed

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    public boolean isPasswordChanged() {
        return passwordChanged;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JLabel newPasswordSeparatorLabel;
    private javax.swing.JLabel confirmPasswordSeparatorLabel;
    private javax.swing.JLabel passwordRequirementLabel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPasswordField newPasswordField;
    // End of variables declaration//GEN-END:variables
}
